[project]
name = "steamquery-backend"
version = "0.1.0"
description = "Backend API for SteamQuery"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.135.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.14.0",
    "httpx>=0.28.0",
    "pymongo>=4.16.0",
    "ruff>=0.15.5",
]
